# url: http://clement-moulin-frier.github.io
# baseurl: /

# Site settings
title: Clément Moulin-Frier
email: clement.moulinfrier@gmail.com
description: "PhD, Engineering of Cognition, Interaction, Learning and Creation."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503  
  secondary-dark: 333


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    font: fa
    url: http://twitter.com/Clement_MF_
  - title: github
    font: fa
    url: http://github.com/clement-moulin-frier
  - title: researchgate
    font: ai
    url: https://www.researchgate.net/profile/Clement_Moulin-Frier
  - title: google-scholar
    font: ai
    url: https://scholar.google.com/citations?user=rBnV60QAAAAJ

# Postal address (add as many lines as necessary)
address:
  - line: Laboratory of Synthetic, Perceptive, Emotive and Cognitive Systems (SPECS)
  - line: Universitat Pompeu Fabraa
  - line: Roc Boronat, 138
  - line: 08018 Barcelona, Spain

scholar:
  sort_by: year
  order: descending
  bibliography: publications.bib
  bibliography_template: <abbr>[]</abbr>{{reference}} {{ entry.note }}
# gems: ['jekyll/scholar']

# Build settings
markdown: kramdown
permalink: none
